package com.baco.ui.containers;

/**
 * CHANGELOG 
 * ---------- 
 * 2011-03-23 : Formato y estilo
 *
 */
/**
 * Implementacion para dialogo de carga
 *
 * @author dnahuat
 */
public class BSDlgLoading extends BSDefaultDialog {

    public BSDlgLoading() {
        super("Dialogo de carga");
        initComponents();
    }

    public BSDlgLoading(String loadingMessage) {
        super("Dialogo de carga");
        initComponents();
        busyLabel.setText(loadingMessage);
    }

    @Override
    public String getUniqueName() {
        return "DlgLoading";
    }

    @Override
    public void setTitle(String loadingMessage) {
        busyLabel.setText(loadingMessage);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jXPanel1 = new org.jdesktop.swingx.JXPanel();
    busyLabel = new org.jdesktop.swingx.JXBusyLabel();

    jXPanel1.setInheritAlpha(false);
    jXPanel1.setOpaque(false);

    busyLabel.setBusy(true);
    busyLabel.setForeground(new java.awt.Color(255, 255, 255));
    busyLabel.setText("Cargando...");
    busyLabel.setFont(new java.awt.Font("SansSerif", 1, 24));

    javax.swing.GroupLayout jXPanel1Layout = new javax.swing.GroupLayout(jXPanel1);
    jXPanel1.setLayout(jXPanel1Layout);
    jXPanel1Layout.setHorizontalGroup(
      jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jXPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(busyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jXPanel1Layout.setVerticalGroup(
      jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jXPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(busyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jXPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jXPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );
  }// </editor-fold>//GEN-END:initComponents
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private org.jdesktop.swingx.JXBusyLabel busyLabel;
  private org.jdesktop.swingx.JXPanel jXPanel1;
  // End of variables declaration//GEN-END:variables
}
