/*
 *   Copyright (c) 2012, Deiby Dathat Nahuat Uc
 *  All rights reserved.
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions are met
 *  1. Redistributions of source code must retain the above copyright
 *  notice, this list of conditions and the following disclaimer.
 *  2. Redistributions in binary form must reproduce the above copyright
 *  notice, this list of conditions and the following disclaimer in the
 *  documentation and/or other materials provided with the distribution.
 *  3. All advertising materials mentioning features or use of this software
 *  must display the following acknowledgement:
 *  This product includes software developed by Deiby Dathat Nahuat.
 *  4. Neither the name of Deiby Dathat Nahuat Uc nor the
 *  names of its contributors may be used to endorse or promote products
 *  derived from this software without specific prior written permission.

 *  THIS SOFTWARE IS PROVIDED BY DEIBY DATHAT NAHUAT UC ''AS IS'' AND ANY
 *  EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 *  WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 *  DISCLAIMED. IN NO EVENT SHALL DEIBY DATHAT NAHUAT UC BE LIABLE FOR ANY
 *  DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 *  (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 *  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 *  ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 *  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 * 
 */
package com.baco.ui.demo;

import com.baco.ui.components.BSBreadcrumbElement;
import com.baco.ui.components.BSBreadcrumbable;
import com.baco.ui.core.BSCoreFactory;
import com.baco.ui.containers.BSDefaultPanel;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.SwingWorker;

/**
 * Panel de demostración
 * @author dnahuat
 *
 * CHANGELOG
 * ----------
 * 2011-03-23 : Se agrega demostracion de BSFancyBreadcrumb
 *
 */
public class BSPnlDemo extends BSDefaultPanel {

   /** Creates new form PnlDemo */
   public BSPnlDemo() {
   }

   /** This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jLabel1 = new javax.swing.JLabel();
      btnCloseSession = new javax.swing.JButton();
      btnShowError = new javax.swing.JButton();
      btnShowWarning = new javax.swing.JButton();
      btnShowInfo = new javax.swing.JButton();
      btnLockHydra = new javax.swing.JButton();
      btnShowDialog = new javax.swing.JButton();
      breadCrumb = new com.baco.ui.components.BSFancyBreadcrumb();
      btnForward = new javax.swing.JButton();
      Reiniciar = new javax.swing.JButton();

      jLabel1.setFont(new java.awt.Font("Dialog", 1, 36));
      jLabel1.setText("PANEL DE PRUEBA 1");

      btnCloseSession.setText("Cerrar sesion");

      btnShowError.setText("Mostrar error");

      btnShowWarning.setText("Mostrar advertencia");

      btnShowInfo.setText("Mostrar informacion");

      btnLockHydra.setText("Bloquear 5 segundos");

      btnShowDialog.setText("Mostrar dialogo");

      breadCrumb.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N

      javax.swing.GroupLayout breadCrumbLayout = new javax.swing.GroupLayout(breadCrumb);
      breadCrumb.setLayout(breadCrumbLayout);
      breadCrumbLayout.setHorizontalGroup(
         breadCrumbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 608, Short.MAX_VALUE)
      );
      breadCrumbLayout.setVerticalGroup(
         breadCrumbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 93, Short.MAX_VALUE)
      );

      btnForward.setText("Adelante");

      Reiniciar.setText("Reiniciar");

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
      this.setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(breadCrumb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                  .addComponent(btnCloseSession, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(btnShowError, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(btnShowWarning, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
               .addGroup(layout.createSequentialGroup()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                     .addComponent(btnShowDialog, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                     .addComponent(btnLockHydra, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                     .addComponent(btnShowInfo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                  .addGap(179, 179, 179))
               .addGroup(layout.createSequentialGroup()
                  .addComponent(Reiniciar)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 501, Short.MAX_VALUE)
                  .addComponent(btnForward)))
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btnCloseSession)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btnShowError)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btnShowWarning)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btnShowInfo)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btnLockHydra)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btnShowDialog)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(breadCrumb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(Reiniciar)
               .addComponent(btnForward))
            .addContainerGap(69, Short.MAX_VALUE))
      );
   }// </editor-fold>//GEN-END:initComponents

   private void setupEvents() {
      btnLockHydra.addActionListener(new ActionListener() {

         @Override
         public void actionPerformed(ActionEvent arg0) {
            new LockWorker().execute();
         }
      });
      btnShowDialog.addActionListener(new ActionListener() {

         @Override
         public void actionPerformed(ActionEvent arg0) {
            new BSDlgDemo().run();
         }
      });
      btnForward.addActionListener(new ActionListener() {

         @Override
         public void actionPerformed(ActionEvent e) {
            breadCrumb.goForward();
         }
      });
      Reiniciar.addActionListener(new ActionListener() {

         @Override
         public void actionPerformed(ActionEvent e) {
            breadCrumb.reset();
         }
      });
   }

   @Override
   public boolean beforeLoad() throws Exception {
      initComponents();
      return true;
   }

   @Override
   public void afterLoad() {
      setupEvents();
      List<BSBreadcrumbable> elements = new ArrayList();
      BSBreadcrumbElement uno = new BSBreadcrumbElement("Uno", false);
      BSBreadcrumbElement dos = new BSBreadcrumbElement("Dos", false);
      BSBreadcrumbElement tres = new BSBreadcrumbElement("Tres", false);
      BSBreadcrumbElement cuatro = new BSBreadcrumbElement("Cuatro", false);
      elements.add(uno);
      elements.add(dos);
      elements.add(tres);
      elements.add(cuatro);
      elements.add(new BSBreadcrumbElement("Tres.1", tres, true));
      elements.add(new BSBreadcrumbElement("Tres.2", tres, true));
      elements.add(new BSBreadcrumbElement("Cuatro.1", cuatro, true));
      elements.add(new BSBreadcrumbElement("Cuatro.2", cuatro, true));
      elements.add(new BSBreadcrumbElement("Uno.1", uno, true));
      elements.add(new BSBreadcrumbElement("Uno.2", uno, true));
      breadCrumb.setElements(elements);


      breadCrumb.setCurrentBGPaint(new GradientPaint(0,
                                                     0,
                                                     new Color(200, 255, 75),
                                                     0,
                                                     30,
                                                     new Color(191, 250, 55)));
      breadCrumb.setFutureBGPaint(new GradientPaint(0, 0,
                                                    new Color(28, 163, 218),
                                                    0, 20, new Color(38, 173,
                                                                     228)));
      breadCrumb.setPastBGPaint(new GradientPaint(0, 0, new Color(120, 121, 115),
                                                  0, 30,
                                                  new Color(130, 131, 126)));
   }

   @Override
   public boolean isSingleInstance() {
      return true;
   }

   @Override
   public String getUniqueName() {
      return "DemoPanel";
   }

   @Override
   public void setLoadDelay(long delay) {
   }

   @Override
   public long getLoadDelay() {
      return 0;
   }

   private class LockWorker extends SwingWorker<Void, Void> {

      private long loadingOID;

      public LockWorker() {
         loadingOID = BSCoreFactory.getCore().showLoading();
      }

      @Override
      protected Void doInBackground() throws Exception {
         Thread.sleep(5000);
         return null;
      }

      @Override
      protected void done() {
         BSCoreFactory.getCore().hideLoading(loadingOID);
      }
   }
   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton Reiniciar;
   private com.baco.ui.components.BSFancyBreadcrumb breadCrumb;
   private javax.swing.JButton btnCloseSession;
   private javax.swing.JButton btnForward;
   private javax.swing.JButton btnLockHydra;
   private javax.swing.JButton btnShowDialog;
   private javax.swing.JButton btnShowError;
   private javax.swing.JButton btnShowInfo;
   private javax.swing.JButton btnShowWarning;
   private javax.swing.JLabel jLabel1;
   // End of variables declaration//GEN-END:variables
}
